name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          VITE_COGNITO_REGION: ${{ secrets.VITE_COGNITO_REGION }}
          VITE_USER_POOL_ID: ${{ secrets.VITE_USER_POOL_ID }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
        run: npm run build

      - name: Upload build artifacts (dist)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  smoke:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          VITE_COGNITO_REGION: ${{ secrets.VITE_COGNITO_REGION }}
          VITE_USER_POOL_ID: ${{ secrets.VITE_USER_POOL_ID }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
        run: npm run build

      - name: Start preview server
        run: |
          nohup npm run preview -- --port 4173 --strictPort >/dev/null 2>&1 &
          echo $! > preview.pid
          for i in {1..30}; do
            if curl -sSf http://localhost:4173/ >/dev/null; then
              echo "Preview UP"; break; fi; sleep 1; done
          curl -sSf http://localhost:4173/ >/dev/null

      - name: Smoke check title
        run: |
          html=$(curl -s http://localhost:4173/)
          echo "$html" | grep -E "Sistema de Pagos|<div|<title>" -i

      - name: Stop preview server
        if: always()
        run: |
          if [ -f preview.pid ]; then
            kill $(cat preview.pid) || true
          fi
